### ISSUE TITLE
Run tests with with `-race` flag and fix race conditions

### ISSUE THREAD

**Issue by CluEleSsUK** [drand/kyber#31]
While replacing circle CI with github actions, @AnomalRoil suggested running the go test runner with the `race` flag to check for race conditions.  This identified some race conditions in DKG code that require investigation and remediating.

During prior investigation, a data access races were identified in the `StatusMatrix` struct implementation.  Adding some generic RW locking worked fine on my local machine and the tests (including race condition testing) passed successfully. 
On the github actions runner however the `TestProtoFull` test in `proto_test.go` appeared to suffer deadlock (albeit the go runtime did not detect this).  Note: this deadlock does not happen without the `-lock` flag 

Some attempts I tried to remedy this:
- updating go to 1.18
- adding test flag GO111MODULE=on
- adding test flag GODEBUG=cgocheck=2 (see https://github.com/golang/go/issues/48402)
- modifying the `resCh` in `TestProtoFull` buffer size to 0 and 2 (see https://github.com/golang/go/issues/48402)
- running tests without make
- implementations of `StatusMatrix`with `RWLock` and vanilla `Lock`
- a variety of timeouts up to 30mins
- running macos-latest and ubuntu-latest github runners

**Comment by AnomalRoil** [comment]
I think this was fixed in #34 in the end.
