### ISSUE TITLE
Wrong threshold in DKG protocol

### ISSUE THREAD

**Issue by si-co** [drand/kyber#43]
In https://github.com/drand/kyber/blob/master/share/dkg/dkg.go#L1095, the threshold should be `n/2 + 1` instead of `(n+1)/2`. This bug likely comes from the DEDIS original VSS implementation (see https://github.com/dedis/kyber/issues/374). If the bug is confirmed, I'm happy to submit a PR.

**Comment by AnomalRoil** [comment]
@si-co  Sorry for not answering earlier! Yes this is a bug that should be corrected, let me know if you plan on sending a PR, otherwise I'll do it at some point in May.
